spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123@123a
    driver-class-name: org.postgresql.Driver
    hibernate:
      hbm2ddl:
        auto: update
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  hikari:
    maximum-pool-size: 10
    connection-timeout: 30000 #30s


